### ISSUE TITLE
Own Navigation go_router BUG

### ISSUE THREAD

**Issue by michalss** [ToyZ-95/another_flutter_splash_screen#5]
same issue here i dont want to use defaultNextScreen at all.. im using go_rotuer and this will break the routing...

![image](https://github.com/ToyZ-95/another_flutter_splash_screen/assets/1000729/5b0997a4-5f10-44aa-b068-3244263c55bf)

giving me errors

```text
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 3036 pos 7: '!pageBased || isWaitingForExitingDecision': A page-based route cannot be completed using imperative api, provide a new list without the corresponding Page to Navigator.pages instead. 
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      _RouteEntry.complete (package:flutter/src/widgets/navigator.dart:3036:7)
#3      NavigatorState._pushReplacementEntry (package:flutter/src/widgets/navigator.dart:4719:56)
#4      NavigatorState.pushReplacement (package:flutter/src/widgets/navigator.dart:4675:5)
#5      Navigator.pushReplacement (package:flutter/src/widgets/navigator.dart:2179:34)
#6      _FlutterSplashScreenState.initState.<anonymous closure> (package:another_flutter_splash_screen/another_flutter_splash_screen.dart:319:17)
#7      new Future.delayed.<anonymous closure> (dart:async/future.dart:427:39)
#8      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#9      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
#10     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
```

no matter i set nextpage to null.. always give me error above ,please allow to make own navigation logic..

**Comment by ToyZ-95** [comment]
@michalss Fixed

Closing this issue as it is fixed in version 1.2.0
